### ISSUE TITLE
[Missing textures] Origins has changed the textures in 1.20+

### ISSUE THREAD

**Issue by aricloverEXTRA** [aricloverEXTRA/Default-Dark-Mode-Expansion#2]
### Description

As known in the title, Origins changed the way they handle their textures in the releases of Origins for 1.20+ Minecraft versions and I decided to fix that problem in the following pull request https://github.com/nebuIr/Default-Dark-Mode/pull/190

and you may ask why I created this Issue when I already made a pull request for it?
well it's just because it seems like no one had created an issue about it or known about it. so I do apologize about showing this random Issue.

### Game versions

1.21, 1.20

### Link to the mod page

https://modrinth.com/mod/origins

**Comment by aricloverEXTRA** [comment]
I was experimenting on the new “1.21” option to make sure everything works as expected.
and I recovered this Issue from my other account since it is flagged.

**Comment by arichornlover** [comment]
![2024-07-20_18 07 14](https://github.com/user-attachments/assets/6a3b72a2-8ae9-475a-b6dd-9e9d83630f67)

**Comment by aricloverEXTRA** [comment]
My Pull Request in NebuIr’s Default Dark Mode will fix this issue. I’m closing this issue since it will be resolved later.
